#version 450 core


layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform samplerCube environmentMap;
layout(set = 0, binding = 1, rgba32f) uniform writeonly imageCube outputIrradianceMap;

const float PI = 3.14159265358979323846;
const float twoPI = 2.0 * PI;
const float halfPI = PI * 0.5;

vec3 getForwardVector(int face)
{
    vec2 st = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5)) / vec2(imageSize(outputIrradianceMap));
    vec2 uv = 2.0 * vec2(st.x, 1.0-st.y) - vec2(1.0); //range [-1,1] for the cubemap faces.

    if (face == 0)
    {
        return vec3(1, uv.y, -uv.x); //plane x = 1
    }
    else if (face == 1)
    {
        return vec3(-1, uv.y, uv.x); //plan x = -1 (imagine a plane facing toward -x)
    }
    else if (face == 2)
    {
        return vec3(uv.x, 1, -uv.y);
    }
    else if (face == 3)
    {
        return vec3(uv.x, -1, uv.y);
    }
    else if (face == 4)
    {
        return vec3(uv.x, uv.y, 1);
    }
    else if (face == 5)
    {
        return vec3(-uv.x, uv.y, -1);
    }

    return vec3(0);
}

void main()
{
    int face = int(gl_GlobalInvocationID.z);

    vec2 size = imageSize(outputIrradianceMap);

    ivec3 pixelCoord = ivec3(gl_GlobalInvocationID.xyz);

    if (pixelCoord.x >= size.x || pixelCoord.y >= size.y || pixelCoord.z >= 6)
    {
        return;
    }

    vec3 normal = normalize(getForwardVector(face));

    vec3 irradiance = vec3(0);

    vec4 color = vec4(0);

    vec3 up    = vec3(0, 1, 0);
    vec3 right = normalize(cross(up, normal));
    up         = normalize(cross(normal, right));

    float sampleDelta = 0.025; //apply to phi and theta -- uniformly spaced samples
    float nrSamples = 0;

    for (float phi = 0; phi < twoPI; phi += sampleDelta)
    {
        float sinPhi = sin(phi);
        float cosPhi = cos(phi);

        for (float theta = 0; theta < halfPI; theta += sampleDelta)
        {
            float sinTheta = sin(theta);
            float cosTheta = cos(theta);

            vec3 tangentSample = vec3(sinTheta * cosPhi, sinTheta * sinPhi, cosTheta);
            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal;

            irradiance += texture(environmentMap, sampleVec).rgb * cosTheta * sinTheta;
            ++nrSamples;
        }
    }

    irradiance = PI * irradiance * (1.0 / float(nrSamples));

    color = vec4(irradiance, 1);

    imageStore(outputIrradianceMap, pixelCoord, color);
}