#version 450 core

//TODO: after testing primitive color output -> layout(set = 2, binding = 0) uniform Sampler2D equirectangularMap;

layout(local_size_x = 16, local_size_y = 16) in;

layout(rgba32f, binding = 0) uniform writeonly imageCube cubeMapOutputImage;

void main()
{
    int face = int(gl_GlobalInvocationID.z);

    ivec3 pixelCoord = ivec3(gl_GlobalInvocationID.xyz);

    vec4 color = vec4(0, 1, 0, 1);

    imageStore(cubeMapOutputImage, pixelCoord, color);
}