#version 450

//since we are processing 2D images, we allocate 16 work items per set of pixels
within the image
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0) uniform sampler2D equirectangularMap;

layout(binding = 1, rgba16f) uniform imageCube cubeMap; //2DImageArray, no prefix = floating point.

layout(push_constant) uniform param
{
    uint faceSize;
} params;

const double PI = 4.0 * atan(1.0);

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    uint face = gl_GlobalInvocationID.z;

    if (pixel.x >= params.faceSize || pixel.y >= params.faceSize)
    {
        return;
    }

    //taking the center of pixel.
    vec2 uv = (vec2(pixel) + 0.5) / params.faceSize;
    uv = uv * 2.0 - 1.0;

    vec3 dir = cubemapDirection(uv, face);
}