#version 450 core


layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform samplerCube environmentMap;
layout(set = 0, binding = 1, rgba32f) uniform writeonly imageCube prefilterMap;


layout (push_constant) uniform pc
{
	float roughness;
};

const float PI = 3.14159265358979323846;

vec3 getForwardVector(int face)
{
    vec2 st = vec2(gl_GlobalInvocationID.xy + vec2(0.5)) / vec2(imageSize(prefilterMap));
    vec2 uv = 2.0 * vec2(st.x, 1.0-st.y) - vec2(1.0); //range [-1,1] for the cubemap faces.

    if (face == 0)
    {
        return vec3(1, uv.y, -uv.x); //plane x = 1
    }
    else if (face == 1)
    {
        return vec3(-1, uv.y, uv.x); //plan x = -1 (imagine a plane facing toward -x)
    }
    else if (face == 2)
    {
        return vec3(uv.x, 1, -uv.y);
    }
    else if (face == 3)
    {
        return vec3(uv.x, -1, uv.y);
    }
    else if (face == 4)
    {
        return vec3(uv.x, uv.y, 1);
    }
    else if (face == 5)
    {
        return vec3(-uv.x, uv.y, -1);
    }

    return vec3(0);
}

float VanDerCorput(uint n, uint base)
{
    float invBase = 1.0 / float(base);
    float denom = 1.0;
    float result = 0.0;

    for (uint i = 0u; i < 32u; ++i)
    {
        if (n > 0u)
        {
            denom = mod(float(n), 2.0);
            result += denom * invBase;
            invBase = invBase / 2.0;
            n = uint(float(n) / 2.0);
        }
    }

    return result;
}


vec2 Hammersley(uint i, uint N)
{
    return vec2(float(i) / float(N), VanDerCorput(i, 2u));
}

vec3 ImportanceSampleGGX( vec2 Xi, vec3 N, float roughness )
{
    float a = roughness * roughness;

    float phi = 2.0 * PI * Xi.x;
    float cosTheta = sqrt( ( 1.0 - Xi.y ) / (1.0 + ( a * a - 1.0 ) * Xi.y ) );
    float sinTheta = sqrt( 1.0 - cosTheta * cosTheta );

    vec3 H;
    H.x = cos(phi) * sinTheta;
    H.y = sin(phi) * sinTheta;
    H.z = cosTheta;

    vec3 up = abs(N.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0);
    vec3 tangent = normalize( cross( up, N ) );
    vec3 bitangent = cross( N, tangent );

    vec3 sampleVec = tangent * H.x + bitangent * H.y + N * H.z;

    return normalize(sampleVec);
}

float DistributionGGX(float NdotH, float roughness)
{
    float a = roughness * roughness;
    float a2 = a * a;

    float denom = NdotH * NdotH * (a2 - 1.0) + 1;
    denom = PI * denom * denom;

    return (a2 / denom);
}

void main()
{
    int face = int(gl_GlobalInvocationID.z);
    ivec3 pixelCoord = ivec3(gl_GlobalInvocationID.xyz);

    vec3 N = normalize(getForwardVector(face));
    vec3 R = N;
    vec3 V = R;

    const uint SAMPLE_COUNT = 1024u;
    float totalWeight = 0.0;
    vec3 prefilteredColor = vec3(0.0);

    ivec2 envMapSize = textureSize(environmentMap, 0);
    float saTexel = 4.0 * PI / ( 6.0 * float( envMapSize.x ) * float( envMapSize.y ) );

    for (uint i = 0u; i < SAMPLE_COUNT; ++i)
    {
        vec2 Xi = Hammersley(i, SAMPLE_COUNT);
        vec3 H = ImportanceSampleGGX(Xi, N, roughness);
        vec3 L = normalize( 2.0 * dot( V, H ) * H - V );

        float NdotH = max( dot( N, H ), 0.0 );
        float HdotV = max( dot( H, V ), 0.0 );

        float NdotL = max( dot( N, L ), 0.0 );
        if ( NdotL > 0.0 )
        {
            float D = DistributionGGX(NdotH, roughness);
            float pdf = ( D * NdotH / (4.0 * HdotV ) ) + 0.0001;

            float saSample = 1.0 / ( float( SAMPLE_COUNT ) * pdf + 0.0001);
            float mipLevel = roughness == 0.0 ? 0.0 : 0.5 * log2( saSample / saTexel );

            prefilteredColor += textureLod(environmentMap, L, mipLevel).rgb * NdotL;

            totalWeight += NdotL;
        }
    }

    prefilteredColor = prefilteredColor / totalWeight;

    vec4 color = vec4(prefilteredColor, 1);

    imageStore(prefilterMap, pixelCoord, color);
}