name: Windows Build
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release, Debug]
        c_compiler: [cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up python for SPIRV-Tools
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run the Python dependency script in shaderc
        run: python ${{github.workspace}}/extern/shaderc/utils/git-sync-deps

      - name: Install the Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set reusable strings for CMake commands
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -G Ninja -B ${{steps.strings.outputs.build-output-dir}}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.buld_type }}
          -S ${{ github.workspace }}

      - name: Build CMake
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} -j 4
